/*
 * HBUTTON_config.h
 *
 *  Created on: Aug 13, 2023
 *      Author: Amr-a
 */

#ifndef HBUTTON_CONFIG_H_
#define HBUTTON_CONFIG_H_



#define BUTTON_PORTA_P0_PULL	PULL_UP
#define BUTTON_PORTA_P1_PULL	PULL_UP
#define BUTTON_PORTA_P2_PULL	PULL_UP
#define BUTTON_PORTA_P3_PULL	PULL_UP
#define BUTTON_PORTA_P4_PULL	PULL_UP
#define BUTTON_PORTA_P5_PULL	PULL_UP
#define BUTTON_PORTA_P6_PULL	PULL_UP
#define BUTTON_PORTA_P7_PULL	PULL_UP

#define BUTTON_PORTB_P0_PULL	PULL_UP
#define BUTTON_PORTB_P1_PULL	PULL_UP
#define BUTTON_PORTB_P2_PULL	PULL_UP
#define BUTTON_PORTB_P3_PULL	PULL_UP
#define BUTTON_PORTB_P4_PULL	PULL_UP
#define BUTTON_PORTB_P5_PULL	PULL_UP
#define BUTTON_PORTB_P6_PULL	PULL_UP
#define BUTTON_PORTB_P7_PULL	PULL_UP

#define BUTTON_PORTC_P0_PULL	PULL_UP
#define BUTTON_PORTC_P1_PULL	PULL_UP
#define BUTTON_PORTC_P2_PULL	PULL_UP
#define BUTTON_PORTC_P3_PULL	PULL_UP
#define BUTTON_PORTC_P4_PULL	PULL_UP
#define BUTTON_PORTC_P5_PULL	PULL_UP
#define BUTTON_PORTC_P6_PULL	PULL_UP
#define BUTTON_PORTC_P7_PULL	PULL_UP

#define BUTTON_PORTD_P0_PULL	PULL_DOWN
#define BUTTON_PORTD_P1_PULL	PULL_DOWN
#define BUTTON_PORTD_P2_PULL	PULL_DOWN
#define BUTTON_PORTD_P3_PULL	PULL_DOWN
#define BUTTON_PORTD_P4_PULL	PULL_DOWN
#define BUTTON_PORTD_P5_PULL	PULL_DOWN
#define BUTTON_PORTD_P6_PULL	PULL_DOWN
#define BUTTON_PORTD_P7_PULL	PULL_DOWN


#endif /* HBUTTON_CONFIG_H_ */
